/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  archived?: boolean;
  authorName?: string;
  averageBookRating?: number;
  bookCover?: string;
  id?: number;
  isbn?: string;
  ownerName?: string;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
