/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedBookResponse {
  authorName?: string;
  averageBookRating?: number;
  bookOwnerReturnApproved?: boolean;
  bookReturned?: boolean;
  id?: number;
  isbn?: string;
  title?: string;
}
