package com.bash.boundbackend.modules.auth.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity


public class Token {

    @Id
    @GeneratedValue
    private Integer id;
    // Generated by the app
    private String token;

    private LocalDateTime createdAt;
    private LocalDateTime expiresAt;
    private LocalDateTime validatedAt;
    private boolean isUsed;

    @ManyToOne
    @JoinColumn(name = "userId", nullable = false)
    private User user;

}
