/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activateUserAccount } from '../fn/authentication-controller/activate-user-account';
import { ActivateUserAccount$Params } from '../fn/authentication-controller/activate-user-account';
import { authenticateUser } from '../fn/authentication-controller/authenticate-user';
import { AuthenticateUser$Params } from '../fn/authentication-controller/authenticate-user';
import { registerUser } from '../fn/authentication-controller/register-user';
import { RegisterUser$Params } from '../fn/authentication-controller/register-user';
import { UserAuthenticationResponse } from '../models/user-authentication-response';


/**
 * Handles user reg and login
 */
@Injectable({ providedIn: 'root' })
export class AuthenticationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerUser()` */
  static readonly RegisterUserPath = '/auth/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerUser$Response(params: RegisterUser$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    const obs = registerUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerUser(params: RegisterUser$Params, context?: HttpContext): Observable<{
}> {
    const resp = this.registerUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `authenticateUser()` */
  static readonly AuthenticateUserPath = '/auth/authenticate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authenticateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticateUser$Response(params: AuthenticateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAuthenticationResponse>> {
    const obs = authenticateUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authenticateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticateUser(params: AuthenticateUser$Params, context?: HttpContext): Observable<UserAuthenticationResponse> {
    const resp = this.authenticateUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserAuthenticationResponse>): UserAuthenticationResponse => r.body)
    );
  }

  /** Path part for operation `activateUserAccount()` */
  static readonly ActivateUserAccountPath = '/auth/activate-account';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `activateUserAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  activateUserAccount$Response(params: ActivateUserAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = activateUserAccount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `activateUserAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  activateUserAccount(params: ActivateUserAccount$Params, context?: HttpContext): Observable<void> {
    const resp = this.activateUserAccount$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
