/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseBorrowedBookResponse } from './models/page-response-borrowed-book-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { UserAuthenticationRequest } from './models/user-authentication-request';
export type { UserAuthenticationResponse } from './models/user-authentication-response';
export type { UserRegistrationRequest } from './models/user-registration-request';
